use_frameworks!

target 'forestAlertView_Example' do
  pod 'forestAlertView', :path => '../'

  target 'forestAlertView_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
